SELECT * 
FROM talbat 
WHERE user_id = 1

ALTER TABLE talbat ADD FOREIGN KEY (user_id) REFERENCES users(id)

ALTER TABLE talbat DROP FOREIGN KEY talbat_ibfk_1

ALTER TABLE talbat ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE 

ALTER TABLE talbat DROP FOREIGN KEY talbat_ibfk_1

ALTER TABLE talbat ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
